collections:
  - name: amazon.aws
    version: 3.0.0
  - name: community.crypto
    version: 2.1.0
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 4.6.1
  - name: community.libvirt
    version: 1.1.0
