- name: Setup hostname
  ansible.builtin.hostname:
    name: "{{ hostvars[inventory_hostname]['instance_name'] }}"
  when: hostvars[inventory_hostname]['instance_name'] is defined

- name: Run the equivalent of "apt-get update" as a separate step for Ubuntu
  apt:
    update_cache: yes
  when: ansible_distribution == 'Ubuntu'

- name: Install base packages
  ansible.builtin.package:
    name: "{{ base_software[ansible_distribution_file_variety] | union(common_software) }}"
    state: present
  register: package_check
  until: package_check is not failed
  retries: 4
  delay: 5

- name: Install Python dependencies
  ansible.builtin.pip:
    name: "{{ python_libraries }}"
    executable: pip3

- name: Setup custom prompt
  ansible.builtin.copy:
    src: prompt.sh
    dest: /etc/profile.d/prompt.sh
    owner: root
    group: root
    mode: '0644'

- name: Make Ubuntu source the prompt file
  ansible.builtin.lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    line: source /etc/profile.d/prompt.sh
  when: ansible_distribution == 'Ubuntu'