- name: Create EC2 Security Group
  amazon.aws.ec2_group:
    name: "{{ ec2_resource_prefix }}-SG"
    description: Security Group for Testing VM
    region: "{{ ec2_region }}"
    vpc_id: "{{ create_vpc.vpc.id }}"
    tags:
      Environment: "{{ ec2_environment }}"
      Name: "{{ ec2_resource_prefix }}-SG"
    rules:
      - proto: tcp
        to_port: 22
        from_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: create_sg
  until: create_sg is not failed
  retries: 5